### ISSUE TITLE
Pre-launch Checklist

### ISSUE THREAD

**Issue by lukad03** [XDgov/MLBias#17]
### Case Study Content
- [ ] Autocoding
- [ ] Imbalances in reporting
- [ ] Bias in computer vision for user authentication

### Build Content
- [ ] Thing One
- [ ] Thing Two
- [ ] Thing Three

### Journey Content
- [ ] Thing One
- [ ] Thing Two
- [ ] Thing Three

### Website Views
- [ ] Case Study View
- [ ] Resources View
- [ ] Journey View
- [ ] Homepage View
- [ ] Quiz View
- [ ] Add Agency Logos - Issue https://github.com/XDgov/MLBias/issues/6

### Marketing
- [ ] Draft comms plan
- [ ] Brief stakeholders on comms plan
- [ ] Send comms one pager to stakeholders for launch day

### Website Infrasctructure
- [x] Meet with Federalist Team
- [ ] Content Approval - Issue https://github.com/XDgov/MLBias/issues/19
- [ ] Secure subdomain from TCO - Issue https://github.com/XDgov/MLBias/issues/2
- [ ] Point subdomain to Federalist
