### ISSUE TITLE
Post-Review Checklist

### ISSUE THREAD

**Issue by lukad03** [XDgov/MLBias#22]
### GitHub Maintenance
- [ ] Clean up issues
- [ ] Add templates for issues and contributing - Issue https://github.com/XDgov/MLBias/issues/4
- [ ] Determine deployment flow w/ ADCOM
